---
- name: Install Nginx on Ubuntu servers
  hosts: all
  become: yes  # This allows the tasks to be run with root privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]
    
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    
    - name: add php support for apache
      apt:
        name: libapache2-mod-php
        state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]
    
    - name: Update dnf package cache
      dnf:
        update_cache: yes
    when: ansible_distribution == "CentOS"

    - name: Install httpd service
      dnf:
        name: httpd
        state: latest
     when: ansible_distribution == "CentOS"

    -name: add php support for httpd
      dnf:
        name: php
        state: latest
     when: ansible_distribution == "CentOS"
