---
- name: Install Nginx on Ubuntu servers
  hosts: all
  become: yes  # This allows the tasks to be run with root privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: absent

    - name: Ensure Nginx service is enabled and running
      systemd:
        name: nginx
        state: absent
        enabled: yes
