---
- hosts: all
  become: yes  # This allows the tasks to be run with root privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]
    

    - name: install updates (CentOS)
      dnf:
        update_only: yes
        update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: web_servers
  become: yes 
  task:

    - name: Install apache
      apt:
        name: 
          - apache2
          - libapache2-mod-php
    
        state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

- hosts: db_servers
  become: yes
  tasks:
    
    - name: Install mariadb for CentOS servers
      dnf:
      name: 
        - mariadb
      state: latest
    when: ansible_distribution in ["CentOS"]
    
    - name: Install mariadb for Ubuntu servers
      apt:
      name:
        - mariadb
      state: latest
    when: ansible_distribution in ["Ubuntu"]

- hosts: file_servers
  become: yes
  tasks:
  
    - name: Install nfs-server
      package:
       name: nfs-server
       state: latest
